/* Each ingredient belongs to a single recipe. */

CREATE TABLE ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INT NOT NULL REFERENCES recipes(id),
  name TEXT NOT NULL,
  amount TEXT NOT NULL
);
